[tool.poetry]
name = "voltorb-flip"
version = "1.0.0"
description = "A minigame of the Goldenrod and Celadon Game Corners in the Korean and Western releases of Pokémon HeartGold and SoulSilver."
authors = ["Antonio Feregrino <antonio.feregrino@gmail.com>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/fferegrino/voltorb-flip"
repository = "https://github.com/fferegrino/voltorb-flip"

[tool.poetry.scripts]
voltorb-flip = 'voltorb_flip.__main__:cli'

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.4"
rich = "^11.2.0"

[tool.poetry.dev-dependencies]
advbumpversion = "^1.2"
bandit = "^1.6"
black = "^22.1.0"
isort = "^4.3"
pylint = "^2.4"
pytest = "^5.2"
pytest-cov = "^2.8"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
